repos:
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.11.2
#    hooks:
#      - id: mypy
#        files: ^src/
#        args: [--ignore-missing-imports, --explicit-package-bases]

#  - repo: https://github.com/PyCQA/bandit
#    rev: 1.7.9
#    hooks:
#      - id: bandit

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix, --show-fixes ]
      # Run the formatter.
      - id: ruff-format
